services:
  myshop_admin.send_email:
      class: MyShop\AdminBundle\Utils\SendMailService
      arguments:
              - "@templating"
              - "@mailer"
              - "%mailer_company_name%"
              - "%mailer_user%"
              - "%user_notifications_list%"

  myshop_admin.upload_image_service:
      class: MyShop\AdminBundle\ImageUtils\UploadImageService
      arguments:
              - "@myshop_admin.check_img"
              - "@myshop_admin.image_name_generator"
              - "%list_size_upload_images%"
      calls:
              - ["setUploadImageRootDir", ["%image_upload_dir%"]]

  myshop_admin.remove_files:
      class: MyShop\AdminBundle\ImageUtils\RemoveFiles
      arguments:
              - "%image_upload_dir%"

  myshop_admin.check_img:
      class: MyShop\AdminBundle\ImageUtils\CheckImg
      arguments:
              - "%upload_image_type_list%"

  myshop_admin.image_name_generator:
      class: MyShop\AdminBundle\ImageUtils\ImageNameGenerator

  myshop_admin.jstree:
      class: MyShop\AdminBundle\Utils\JSTreeCategoryService
      arguments:
              - "@doctrine"
              - "MyShopDefaultBundle:Category"

  myshop_admin.my_twig_extension:
      class: MyShop\AdminBundle\Twig\MyCustomExtension
      public: false
      tags:
              - { name: twig.extension }